// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using assignment.Data;

#nullable disable

namespace assignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250922153914_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("assignment.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 22, 15, 39, 13, 197, DateTimeKind.Utc).AddTicks(6938),
                            Description = "Comfortable cotton t-shirt perfect for everyday wear",
                            Image = "https://example.com/tshirt.jpg",
                            Name = "Classic T-Shirt",
                            Price = 19.99m,
                            UpdatedAt = new DateTime(2025, 9, 22, 15, 39, 13, 197, DateTimeKind.Utc).AddTicks(7150)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 22, 15, 39, 13, 197, DateTimeKind.Utc).AddTicks(7301),
                            Description = "High-quality denim jeans with a modern fit",
                            Image = "https://example.com/jeans.jpg",
                            Name = "Denim Jeans",
                            Price = 79.99m,
                            UpdatedAt = new DateTime(2025, 9, 22, 15, 39, 13, 197, DateTimeKind.Utc).AddTicks(7301)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 22, 15, 39, 13, 197, DateTimeKind.Utc).AddTicks(7303),
                            Description = "Light and airy summer dress perfect for warm weather",
                            Image = "https://example.com/dress.jpg",
                            Name = "Summer Dress",
                            Price = 49.99m,
                            UpdatedAt = new DateTime(2025, 9, 22, 15, 39, 13, 197, DateTimeKind.Utc).AddTicks(7304)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
